### ISSUE TITLE
Set up CI to perform releases

### ISSUE THREAD

**Issue by dominics** [vital-software/scala-redox#33]
Similar to what we've done with our other Scala libs, this library should support versioning the project during the CI build of master commits:

```yaml
  - name: ":sbt: Release new version"
    branches: master
    command:
      - git checkout -B ${BUILDKITE_BRANCH}
      - git branch -u origin/${BUILDKITE_BRANCH}
      - git config branch.${BUILDKITE_BRANCH}.remote origin
      - git config branch.${BUILDKITE_BRANCH}.merge refs/heads/${BUILDKITE_BRANCH}
      - sbt -batch "release with-defaults skip-tests"
```

The CI system should have Sonatype access, and use it to publish artifacts.
